on: [pull_request]

jobs:
  hello_world_job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Reviewing Code 
        id: hello
        uses: akshay-rao-h2/test-github-actions@v1.25
        with:
          pr-link: ${{ github.event.number }}
          token: ${{ github.token }}
          AITOKEN: '7f7787fc0e965160e2eadb2011b5a02c39eb761fd518c5e2107f6788b958fb60988c98f8ca954bcb6452a5b219545cf6be62900cc06cb49af4bf28c5333b8d01c68571d46fc15094f974d60cd51c161acdf2fbd664270bc63fb3c0d8c86d44b452fb55d59a791024b44ede9fbc13145f5292492f719c7e1f4b99ee5f50f5d47f9379a64a89c9f516f0abb13c393d425c349c38'
          repo: ${{ github.repository }}
          commit-id: ${{ github.sha }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"