on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: akshay-rao-h2/test-github-actions@v1.13
        with:
          who-to-greet: 'Mona the Octocat12'
          pr-link: ${{ github.event.number }}
          token: ${{ github.token }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"